# Generated by Django 4.1.1 on 2022-09-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='engine',
            field=models.FloatField(default=0.0, max_length=4),
        ),
        migrations.AddField(
            model_name='post',
            name='wheel',
            field=models.CharField(choices=[('RWD', 'RWD'), ('FWD', 'FWD'), ('4WD', '4WD')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='post',
            name='year',
            field=models.IntegerField(default=2000),
        ),
    ]
