# Generated by Django 4.1.1 on 2022-09-25 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravan', '0002_post_engine_post_wheel_post_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='wheel',
            field=models.CharField(choices=[('4WD', '4WD'), ('RWD', 'RWD'), ('FWD', 'FWD')], max_length=5),
        ),
        migrations.AlterField(
            model_name='post',
            name='year',
            field=models.IntegerField(default=2010),
        ),
    ]
