# Generated by Django 4.1.1 on 2022-09-25 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravan', '0006_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='price',
            field=models.IntegerField(default=1000000),
        ),
    ]
