# Generated by Django 4.1.1 on 2022-09-25 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caravan', '0008_alter_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.CharField(choices=[('Седаны', 'Седаны'), ('Гибриды', 'Гибриды'), ('Кроссоверы', 'Кроссоверы'), ('Универсалы', 'Универсалы'), ('Хэтчбеки', 'Хэтчбеки'), ('Внедорожники', 'Внедорожники')], default='', max_length=30),
        ),
    ]
